version: "3.8"

services:
    v-atlas-client:
        image: ghcr.io/v-atlas/v-atlas-poc/v-atlas-identity-client:latest
        build:
            context: .
            dockerfile: Dockerfile

        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"

        restart: unless-stopped
